stages:
  data_ingestion:
    cmd: python src/FeatherCareOps/pipeline/stg_01_data_ingestion.py
    deps:
      - src/FeatherCareOps/pipeline/stg_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Chicken_disease

  prepare_base_model:
    cmd: python src/FeatherCareOps/pipeline/stg_02_prepare_base_model.py
    deps:
      - src/FeatherCareOps/pipeline/stg_02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model

  training:
    cmd: python src/FeatherCareOps/pipeline/stg_03_training.py
    deps:
      - src/FeatherCareOps/pipeline/stg_03_training.py
      - src/FeatherCareOps/components/prepare_base_model.py
      - config/config.yaml
      - artifacts/data_ingestion/Chicken_disease
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS 
      - BATCH_SIZE
      - ARUGMENTATION
    outs:
      - artifacts/training/models.h5

  evaluation:
    cmd: python src/FeatherCareOps/pipeline/stg_03_evaluation.py
    deps:
      - src/FeatherCareOps/pipeline/stg_03_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/Chicken_disease 
      - artifacts/training/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
      - scores.json
          cache: false
